# Generated by Django 2.2.7 on 2020-12-22 09:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 22, 9, 35, 35, 564631, tzinfo=utc)),
        ),
    ]
