# Generated by Django 2.2.7 on 2020-12-27 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0003_auto_20201222_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 27, 15, 48, 0, 668154)),
        ),
    ]
